#define AMBIENT_OCCLUSION_STRENGTH      0.01
#define AMBIENT_OCCLUSION_COLOR_DELTA   vec3(0.8)
#define BACKGROUND_COLOR                vec3(0.6, 0.6, 0.9)
#define DIFFUSE_ENABLED                 1
#define DIFFUSE_ENHANCED_ENABLED        1
#define EPSILON                         0.0001
#define FOG_ENABLED                     1
#define GLOW_ENABLED                    1
#define GLOW_COLOR_DELTA                vec3(-0.2, 0.5, -0.2)
#define GLOW_SHARPNESS                  4.0 
#define LIGHT_COLOR                     vec3(1.0, 1.0, 1.0)
#define LIGHT_DIRECTION                 vec3(-0.36, 0.48, 0.80)
#define MAX_STEPS                       500
#define MAX_DIST                        100.0
#define MIN_DIST                        0.001
#define SENSOR_DISTANCE                 4.5
#define SHADOWS_ENABLED                 0
#define SHADOW_DARKNESS                 0.8
#define SHADOW_SHARPNESS                16.0
#define SPECULAR_HIGHLIGHT              40
#define SUN_ENABLED                     1
#define SUN_SIZE                        0.005
#define SUN_SHARPNESS                   2.0
#define VIGNETTE_STRENGTH               0.5

