// DONT CHANGE DATATYPES FOR THE DEFINES
#define AA                              1.0
#define AMBIENT_STRENGTH                0.08
#define BACKGROUND_COLOR                vec3(0.0,0.0,0.0)
#define CAMERA_SENSOR_DISTANCE          3.0
#define EPSILON                         0.0002
#define FOG_ENABLED                     1
#define FOG_MULTIPLIER                  0.8
#define GAMMA                           2.2
#define GLOBAL_LIGHT                    1
#define GLOBAL_LIGHT_COLOR              vec3(1.0)
#define GLOBAL_LIGHT_DIRECTION          vec3(-0.36, 0.48, 0.80)
#define MAX_DISTANCE                    256.0
#define MAX_STEPS                       512
#define SPECULAR_HIGHLIGHT              32
#define SHADOW_ENABLED                  0
#define SHADOW_DARKNESS                 0.8
#define SHADOW_HARDNESS                 8.0
#define REFLECTION                      0
#define REFLECTION_MAX_DISTANCE         8.0
#define REFLECTION_MAX_STEPS            64
#define RENDER_SUN                      1
#define RENDER_SUN_SHARPNESS            2.0
#define RENDER_SUN_SIZE                 0.005